### PR TITLE
"Fix" rendering of single camera

### LINKED ISSUE #458: first calibrated camera visibility
Open/create a project that does not have cameras in TS GUI. Ensure a scene mesh is loaded. Pick a frame and calibrate a camera for it using six 3D-2D point correspondences. Observe the log for a successful calibration and a view re-projection on the mesh. Although camera is calibrated and inserted it is not visible in the 3D viewer. Calibrate a camera for a different frame, and observe that now two camera frustums are visible in the 3D viewer. The idea is to display the first calibrated camera frustum without having to calibrate any additional ones.

### PR DESCRIPTION
**Pull request by mwoehlke-kitware**
Don't update the camera path if there is only one camera. Besides being pointless (as we obviously cannot render a path with only one point), for some mysterious reason trying to do so prevents the other actors from rendering at all, resulting in not being able to render a single camera.

This feels like a definite kludge, but seems to work...

Fixes #458.

### CODE REVIEW

File: gui/vtkMaptkCameraRepresentation.cxx [hunk 1]
```diff
@@ -336,8 +336,10 @@ void vtkMaptkCameraRepresentation::Update()
                        this->Internal->ActivePolyData.GetPointer());
   }
 
-  // Path Actor
-  if (this->Internal->PathNeedsUpdate)
+  // Path Actor... only update if we have more than one camera, since we
+  // obviously can't draw lines for a single point, and for some reason having
+  // only one point causes the other actors to fail to render
+  if (this->Internal->PathNeedsUpdate && this->Internal->Cameras.size() > 1)
```
Comment (mleotta) [inline gui/vtkMaptkCameraRepresentation.cxx:342]: I wonder if we still need to 
```
this->Internal->PathPolyData->Reset();
this->Internal->PathPolyData->Modified();
this->Internal->PathNeedsUpdate = false;
```
if there is only one camera

Comment (mwoehlke-kitware) [reply gui/vtkMaptkCameraRepresentation.cxx:340]: It seemed to work, but I didn't test having two cameras and removing one; conceivably that might be broken.

**Comment by borovik135** [comment]
verified that with this change a single calibrated camera frustum now appears in the 3D viewer, adding more calibrated cameras result in more frustums to appear connected by a path, hence satisfying the manual calibration task requirements on camera frustum rendering

**Review by mleotta — APPROVED** [review]
